spring:
  application:
    name: oa-server
  datasource:
    url: jdbc:mysql://60.204.222.228:3306/oa_cooperate_with?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: blzg330513
server:
  port: 8155
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl